version: "3"
services:
  openconnect:
    image: markusmcnugen/openconnect:latest
    container_name: openconnect
    hostname: openconnect
    privileged: true
    restart: always
    ports:
      - 4443:4443
      - 4443:4443/udp
    volumes:
      - ./config:/config